### PR TITLE
Overlay opacity and message text color options added for ios

### PR DESCRIPTION
**Pull request by semirturgay**
1-) When the background is white on ios apps the message and also spinner cannot be seen because of the opacity of overlay. So I made the opacity of overlay as optional parameter. 
2-) Also I added optional text color for ios for better customization.

### CODE REVIEW

**Comment by Paldom** [comment]
Thanks!

**Comment by AllenConquest** [comment]
Although my command `cordova plugins add cordova-plugin-spinner-dialog` says that it has pulled version 1.3.1 the spinner.js file does not have the ios options parameter. I don't understand why this is not working. Do I need to install directly from github instead?

**Comment by semirturgay** [comment]
Hi Allen  it is realy weird. 
can you remove the plugin and try to add it with repository's url as follow :
`cordova plugins add cordova plugins add cordova-plugin-spinner-dialog`

**Comment by AllenConquest** [comment]
@semirturgay I put another issue #31 where I explained that using the direct pull from github works fine, but using the recommended command gave these funny results. How can that happen?

**Pull request merged**
