### PR TITLE
Make the dialog background color transparent on Android 5.x

### PR DESCRIPTION
**Pull request by subeebot**
Currently this fix only works in "fixed" mode. Tested on Nexus 5X.

### CODE REVIEW

**Comment by aszmyd** [comment]
+1

**Comment by semirturgay** [comment]
wouldn't be better make the color optional by adding a color option paramater to `spinner.js`.
As i did at [#26](https://github.com/Paldom/SpinnerDialog/pull/26) for ios.

**Comment by Paldom** [comment]
Thanks @subeebot! @semirturgay you're right, I'll try to solve.

**Comment by kevin-sharktek** [comment]
I am still facing this issue even with the updated code.

screenshot_2016-05-09-14-46-50 1

Here is the code that is supposed to fix it:

code

**Comment by maurozac** [comment]
just modify SpinnerDialog.java in the same mood:

```
if (title == null && message == null) {
    dialog.setContentView(new ProgressBar(cordova.getActivity()));
    // add this here:
    dialog.getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));
}
```

**Comment by datazen** [comment]
problem has regressed.  I am seeing this again with Android and the fix posted here is already in the code.

**Pull request merged**
